server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_manager
    username: paytak
    password: code
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.paytakcode.inventorymanager.api.v1: info

